version: '3.8'

services:
  backend: &backend
    build:
      context: ./backend
      dockerfile: ./Dockerfile.dev
    image: backend
    restart: always
    env_file:
      - .env.ini.backend
    depends_on:
      - postgres
    volumes:
      - local_data_backups:/backups
      - ./backend:/app
    ports:
      - "8000:80"
    environment:
      - SOME_VARIABLE=20
    entrypoint: bash -c "just some_make_command"

  backend-2:
    <<: *backend
    ports:
      - "8001:81"
    environment:
      - SOME_VARIABLE_2=20
    entrypoint: bash -c "just some_make_command_2"

  postgres:
    image: postgres:15.1
    restart: always
    env_file:
      - .env.ini.backend
    volumes:
      - local_postgres_data:/var/lib/postgresql/data
      - local_data_backups:/backups
    expose:
      - 5432

volumes:
  local_postgres_data:
  local_data_backups:
